# Generated by Django 4.0.2 on 2022-02-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier',
            new_name='supplier_id',
        ),
    ]
