# Generated by Django 4.0.1 on 2022-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
