# Generated by Django 4.0.2 on 2022-02-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_supplier_purchase_supplier_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
