# Generated by Django 4.0.1 on 2022-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supplier_address_supplier_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('invoice', models.CharField(max_length=30)),
                ('total', models.PositiveIntegerField()),
            ],
        ),
    ]
