# Generated by Django 4.0.2 on 2022-02-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='account', max_length=255),
            preserve_default=False,
        ),
    ]
