# Generated by Django 4.0.2 on 2022-02-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier Account'), ('CUSTOMER', 'Customer Account'), ('CASH', 'Cash Account'), ('BANK', 'Bank Account'), ('MOBILE MONEY', 'Mobile Money Account')], default='CASH', max_length=255),
            preserve_default=False,
        ),
    ]
