# Generated by Django 4.0.1 on 2022-01-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
    ]
