# Generated by Django 4.0.2 on 2022-02-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_account_options_account_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='purchase',
            new_name='purchase_id',
        ),
    ]
