# Generated by Django 4.0.1 on 2022-01-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['date', 'id']},
        ),
    ]
