# Generated by Django 4.0.2 on 2022-02-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_purchase_inventory_purchase_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product',
            new_name='product_id',
        ),
    ]
