# Generated by Django 4.0.2 on 2022-02-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expense_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='account',
            new_name='account_id',
        ),
    ]
