# Generated by Django 4.0.2 on 2022-02-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_account_expense_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='core.account'),
            preserve_default=False,
        ),
    ]
