# Generated by Django 4.0.1 on 2022-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cost_price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
