# Generated by Django 4.0.1 on 2022-01-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_purchaseitem_batch_number_purchaseitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['date', '-id']},
        ),
    ]
