# Generated by Django 4.0.2 on 2022-02-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_supplier_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='availale_units',
            new_name='available_units',
        ),
    ]
