# Generated by Django 4.0.2 on 2022-02-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_purchase_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='account_id',
            new_name='account',
        ),
    ]
