# Generated by Django 4.0.2 on 2022-02-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_account_id_supplier_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
