# Generated by Django 4.0.1 on 2022-01-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_sale_product_remove_sale_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseItem',
            new_name='Inventory',
        ),
    ]
