# Generated by Django 4.0.1 on 2022-01-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_purchaseitem_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.inventory'),
            preserve_default=False,
        ),
    ]
