# Generated by Django 4.0.1 on 2022-01-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_saleitem_product_saleitem_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
