# Generated by Django 4.0.1 on 2022-01-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_packsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='inventory',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.packsize'),
            preserve_default=False,
        ),
    ]
