# Generated by Django 4.0.1 on 2022-01-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_saleitem_inventory_saleitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='packsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_sizes', to='core.product'),
        ),
    ]
