# Generated by Django 4.0.1 on 2022-01-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_expenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
