# Generated by Django 4.0.1 on 2022-01-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_accountitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountitem',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
    ]
