# Generated by Django 4.0.1 on 2022-01-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_accountitem_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_price',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
