# Generated by Django 4.0.1 on 2022-01-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_saleitem_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packsize',
            options={'ordering': ['product__name']},
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='product',
            new_name='pack_size',
        ),
    ]
