# Generated by Django 4.0.1 on 2022-01-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_packsize_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='availale_units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
